---
name: ci-issue-260-refresh
on: push
jobs:
  test:
    # if: false
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Install gotestsum
        run: go get gotest.tools/gotestsum@v0.4.0
      - name: Run tests
        run: |
          eval $(go env)
          mkdir -p ~/junit/
          ${GOPATH}/bin/gotestsum -f standard-verbose --junitfile ~/junit/unit-tests.xml -- -race github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh -count=20 -run TestRefreshClient_Stress
      - name: Run tests[2]
        run: |
          eval $(go env)
          ${GOPATH}/bin/gotestsum -f standard-verbose --junitfile ~/junit/unit-tests.xml -- -race github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh -count=20 -run TestRefreshClient_Stress
      - name: Run tests[3]
        run: |
          eval $(go env)
          ${GOPATH}/bin/gotestsum -f standard-verbose --junitfile ~/junit/unit-tests.xml -- -race github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh -count=20 -run TestRefreshClient_Stress
      - name: Run tests[4]
        run: |
          eval $(go env)
          ${GOPATH}/bin/gotestsum -f standard-verbose --junitfile ~/junit/unit-tests.xml -- -race github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh -count=20 -run TestRefreshClient_Stress
  test-win:
    # if: false
    name: test-win
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Install gotestsum
        run: go get gotest.tools/gotestsum@v0.4.0
      - name: Run tests
        run: |
          $env:Path += ";$(go env GOPATH)\bin"
          mkdir $home/junit
          gotestsum -f standard-verbose --junitfile $home\junit\unit-tests.xml -- -race github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh -count=20 -run TestRefreshClient_Stress
      - name: Run tests[2]
        run: |
          $env:Path += ";$(go env GOPATH)\bin"
          gotestsum -f standard-verbose --junitfile $home\junit\unit-tests.xml -- -race github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh -count=20 -run TestRefreshClient_Stress
      - name: Run tests[3]
        run: |
          $env:Path += ";$(go env GOPATH)\bin"
          gotestsum -f standard-verbose --junitfile $home\junit\unit-tests.xml -- -race github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh -count=20 -run TestRefreshClient_Stress
      - name: Run tests[4]
        run: |
          $env:Path += ";$(go env GOPATH)\bin"
          gotestsum -f standard-verbose --junitfile $home\junit\unit-tests.xml -- -race github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh -count=20 -run TestRefreshClient_Stress
  test-osx:
    name: test-osx
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Install gotestsum
        run: go get gotest.tools/gotestsum@v0.4.0
      - name: Run tests
        run: |
          eval $(go env)
          mkdir -p ~/junit/
          ${GOPATH}/bin/gotestsum -f standard-verbose --junitfile ~/junit/unit-tests.xml -- -race github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh -count=20 -run TestRefreshClient_Stress
      - name: Run tests[2]
        run: |
          eval $(go env)
          ${GOPATH}/bin/gotestsum -f standard-verbose --junitfile ~/junit/unit-tests.xml -- -race github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh -count=20 -run TestRefreshClient_Stress
      - name: Run tests[3]
        run: |
          eval $(go env)
          ${GOPATH}/bin/gotestsum -f standard-verbose --junitfile ~/junit/unit-tests.xml -- -race github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh -count=20 -run TestRefreshClient_Stress
      - name: Run tests[4]
        run: |
          eval $(go env)
          ${GOPATH}/bin/gotestsum -f standard-verbose --junitfile ~/junit/unit-tests.xml -- -race github.com/networkservicemesh/sdk/pkg/networkservice/common/refresh -count=20 -run TestRefreshClient_Stress
